import {
    PiHouseLineDuotone,
    PiUsersThreeDuotone,
    PiBuildingsDuotone,
    PiBuildingOfficeDuotone,
    PiHandshakeDuotone,
    PiClipboardTextDuotone,
    PiCalendarCheckDuotone,
    PiPackageDuotone,
    PiChartBarDuotone,
    PiFileTextDuotone,
    PiGearSixDuotone,
    PiKanbanDuotone,
    PiUserCircleDuotone,
    PiListChecksDuotone,
    PiFunnelDuotone,
    PiBriefcaseDuotone,
    PiSquaresFourDuotone,
    PiFlowArrowDuotone,
    PiTreeStructureDuotone,
    PiChartLineUpDuotone,
    PiBellDuotone,
    PiChatCircleDuotone,
    PiFilesDuotone,
    PiLightningDuotone,
    PiMagnifyingGlassDuotone,
    PiReceiptDuotone,
    PiUsersDuotone,
} from 'react-icons/pi'
import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    home: <PiHouseLineDuotone />,
    portfolio: <PiBriefcaseDuotone />,
    dashboard: <PiHouseLineDuotone />,
    contacts: <PiUsersThreeDuotone />,
    companies: <PiBuildingsDuotone />,
    deals: <PiHandshakeDuotone />,
    orders: <PiClipboardTextDuotone />,
    activities: <PiCalendarCheckDuotone />,
    products: <PiPackageDuotone />,
    reports: <PiChartBarDuotone />,
    documents: <PiFileTextDuotone />,
    settings: <PiGearSixDuotone />,
    kanban: <PiKanbanDuotone />,
    members: <PiUserCircleDuotone />,
    list: <PiListChecksDuotone />,
    organization: <PiBuildingOfficeDuotone />,
    pipelines: <PiFunnelDuotone />,
    projects: <PiSquaresFourDuotone />,
    automation: <PiFlowArrowDuotone />,
    automationV2: <PiTreeStructureDuotone />,
    reportsChart: <PiChartLineUpDuotone />,
    chat: <PiChatCircleDuotone />,
    search: <PiMagnifyingGlassDuotone />,
    notifications: <PiBellDuotone />,
    // Phosphor-имена, которые присылает backend в manifest.navigation[].icon
    // (module-registry). Без них navigationIcon[icon]=undefined → иконки в меню нет.
    PiChartLineUp: <PiChartLineUpDuotone />,
    PiChartBar: <PiChartBarDuotone />,
    PiUsers: <PiUsersDuotone />,
    PiBuildings: <PiBuildingsDuotone />,
    PiKanban: <PiKanbanDuotone />,
    PiReceipt: <PiReceiptDuotone />,
    PiCalendarCheck: <PiCalendarCheckDuotone />,
    PiPackage: <PiPackageDuotone />,
    PiFiles: <PiFilesDuotone />,
    PiLightning: <PiLightningDuotone />,
    PiMagnifyingGlass: <PiMagnifyingGlassDuotone />,
    PiBell: <PiBellDuotone />,
    PiChatCircle: <PiChatCircleDuotone />,
}

export default navigationIcon
